name: Update Calendar

permissions:
  contents: read

on:
  # Allow manual triggers
  workflow_dispatch:

  # Schedule the workflow to run daily at 08:15
  schedule:
    - cron: '15 8 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UNTISGOOGLESYNC_AESKEY: ${{ secrets.UNTISGOOGLESYNC_AESKEY }}
      UNTISGOOGLESYNC_CALENDARTOSTORE: ${{ secrets.UNTISGOOGLESYNC_CALENDARTOSTORE }}
      UNTISGOOGLESYNC_GOOGLESERVICEACCOUNTJSON: ${{ secrets.UNTISGOOGLESYNC_GOOGLESERVICEACCOUNTJSON }}
      UNTISGOOGLESYNC_ULOGIN_PASSWORD: ${{ secrets.UNTISGOOGLESYNC_ULOGIN_PASSWORD }}
      UNTISGOOGLESYNC_ULOGIN_SCHOOL: ${{ secrets.UNTISGOOGLESYNC_ULOGIN_SCHOOL }}
      UNTISGOOGLESYNC_ULOGIN_SERVER: ${{ secrets.UNTISGOOGLESYNC_ULOGIN_SERVER }}
      UNTISGOOGLESYNC_ULOGIN_USERNAME: ${{ secrets.UNTISGOOGLESYNC_ULOGIN_USERNAME }}
      UNTISGOOGLESYNC_USEOAUTH: ${{ secrets.UNTISGOOGLESYNC_USEOAUTH }}

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: 'gradle'

      # Step 3: Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Step 3: Set execute permission for gradlew
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      # Step 4: Build the project
      - name: Build Project
        run: ./gradlew build

      # Step 5: Update Calendar
      - name: Update Calendar
        run: java -cp "build/classes/java/main" dataHandlement.Main
